# Imagen base de Node
FROM node:20

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Archivos del package (dependencias)
COPY package*.json ./

# Instalar las dependencias
RUN npm install

# Copiar el código
COPY . .

# Exponer el puerto que Vite usa por defecto
EXPOSE 5173

# Comando por defecto al iniciar el contenedor
CMD ["npm", "run", "dev"]