services:
  # Frontend service
  frontend: 
    build: ./frontend
    container_name: frontend_container
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"

  # Backend backend service
  backend: 
    build: ./backend
    container_name: backend_container
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
